            ZZZZZZZZZZZZZZZZZZZZZ
          ZZZZZ______________ZZZZZZ
        ZZZZZ____________________ZZZZ
      ZZZZZ_______________________ZZZZZ
    ZZZZZ___________________________ZZZZ
   ZZZZ______________________________ZZZZ
  ZZZ__________________________________ZZZ
 ZZZ____________________________________ZZZ
ZZZZ____________________________________ZZZ
ZZZ_____________________________________ZZZ
ZZZ_____________________________________ZZZ
ZZZ_____________________________________ZZZ
ZZZ_____________________________ZZ______ZZZ
ZZZ___________________________ZZZZZ_____ZZZ
ZZZ________________________ZZZZZZZZZ__ZZZZZ
ZZZZ____ZZZ______________ZZZZZZZZZZZZ_ZZZZ
ZZZZ___ZZZZZZ___________ZZZZZZZZZZZZZ_ZZZ
ZZZZ__ZZZZZZZZZZ_______ZZZZZZZZZZZZZ__ZZ
ZZZZ__ZZZZZZZZZZZ______ZZZZZZZZZZZZ___ZZ
 ZZZ___ZZZZZZZZZZZ______ZZZZZZZZZZ____ZZ
 ZZZ____ZZZZZZZZZ_ZZZZZ___ZZZZZZ____ZZZZ
  ZZZ____ZZZZZZZ__ZZZZZZ___________ZZZZ
   ZZZZZ__________Z__ZZZ_____ZZZZZZZZZ
    ZZZZZZZZ__________ZZ____ZZZZZZZZ
     ZZZZZZZZ_____________ZZZZZ
          ZZZ__Z___Z___Z__ZZZ
          ZZZ_ZZZ_ZZZ_ZZZ_ZZZ
          ZZZ_ZZZ_ZZZ_ZZZ_ZZZ
          ZZZ_ZZZ_ZZZ_ZZZ_ZZZ
           ZZZZZZZZZZZZZZZZZ
              ZZZZZZZZZZZ 
